version: '3.9'

services:
  db:
    image: mysql:8.0.21
    container_name: sales_management_db
    ports:
      - ${DB_PORT:-3306}:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_DATABASE:-sales_management}
